[project]
name = "mcp-debug-client"
version = "0.1.0"
description = "Minimal MCP client for debugging and testing"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp-use>=1.2.5",
    "langchain-openai>=0.2.0",
]
